length:
  min_5: 5
  max_250: 250
  min_3: 3
  max_100: 100
  min_8: 8
  max_100: 100
checked_1: "1"
show_10: 10
size_80: 80
less_than_5: 5
format_img: ["image/png", "image/jpg", "image/jpeg"]
img:
  size_arr_500: [500, 500]
  size_50: 50
